[package]
name = "rambda"
description = "A Rust Lambda Calculus interpreter"
authors = [
    "Levi <leviiloviee@gmail.com>"
]
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
